name: Upload Python Package to PyPI when a Release is Created

on:
  release:
    types: [created]

jobs:
  pypi-publish:
    name: Publish release to PyPI
    runs-on: ubuntu-latest
    environment:
      name: pypi
      url: https://pypi.org/p/starkfmpy
    permissions:
      id-token: write
    steps:
      - uses: actions/checkout@v4
      - name: Install uv
        uses: astral-sh/setup-uv@v5
      - name: 'Set up Python'
        uses: actions/setup-python@v5
        with:
          python-version-file: 'pyproject.toml'
      - name: Install the project
        run: uv sync --all-extras --dev
      - name: Build package
        run: |
          uv build
      - name: Publish package distributions to PyPI
        run: |
          uv publish
